# Generated by Django 4.2 on 2026-03-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='tiendas/')),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('numero_direccion', models.CharField(blank=True, max_length=100)),
                ('tipo_via', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
    ]
