# Generated by Django 4.2 on 2026-03-17 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 15 dígitos.', regex='^\\+?\\d{7,15}$')])),
                ('categoria', models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('carnes', 'Carnes'), ('bebidas', 'Bebidas'), ('lacteos', 'Lácteos'), ('granos', 'Granos'), ('cereales', 'Cereales'), ('oleaginosas', 'Oleaginosas'), ('ornamentales', 'Ornamentales'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tiendas/logos/')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='tiendas/portadas/')),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('numero_direccion', models.CharField(blank=True, max_length=100)),
                ('tipo_via', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('rating_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['nombre'], name='tiendas_tie_nombre_61bae7_idx'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['categoria'], name='tiendas_tie_categor_74ff3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['activo'], name='tiendas_tie_activo_85452c_idx'),
        ),
    ]
