# Generated by Django 4.2 on 2026-03-13 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'ordering': ['-creada_en'], 'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/logos/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='rating_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tienda',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='total_productos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='barrio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('carnes', 'Carnes'), ('bebidas', 'Bebidas'), ('lacteos', 'Lácteos'), ('granos', 'Granos'), ('cereales', 'Cereales'), ('oleaginosas', 'Oleaginosas'), ('ornamentales', 'Ornamentales'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/portadas/'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 15 dígitos.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['nombre'], name='tiendas_tie_nombre_61bae7_idx'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['categoria'], name='tiendas_tie_categor_74ff3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['activa'], name='tiendas_tie_activa_dd163c_idx'),
        ),
    ]
