# Generated by Django 4.2 on 2026-02-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(default='Todas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='email',
            field=models.EmailField(default='email@tienda.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(default='3000000000', max_length=20),
            preserve_default=False,
        ),
    ]
