# Generated by Django 4.2 on 2026-02-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_tienda_categoria_tienda_email_tienda_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/'),
        ),
    ]
