# Generated by Django 4.2 on 2026-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_alter_tienda_options_tienda_actualizada_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
