# Generated by Django 4.2 on 2026-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_tienda_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='informacion_adicional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_via',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
