# Generated by Django 4.2 on 2026-03-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0004_tienda_barrio_tienda_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='numero_direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
