# Generated by Django 4.2 on 2026-03-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0005_tienda_numero_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
    ]
