# Generated by Django 4.2 on 2026-03-17 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('carnes', 'Carnes'), ('bebidas', 'Bebidas'), ('otros', 'Otros'), ('lacteos', 'Lácteos'), ('granos', 'Granos'), ('ornamentales', 'Ornamentales'), ('cereales', 'Cereales'), ('oleaginosas', 'Oleaginosas')], default='otros', max_length=50)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras'), ('unidad', 'Unidad'), ('litro', 'Litros'), ('mililitro', 'Mililitros')], default='kg', max_length=20)),
                ('tipo_producto', models.CharField(choices=[('solido', 'Sólido'), ('liquido', 'Líquido')], default='solido', max_length=20)),
                ('descuento', models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento')),
                ('fecha_caducidad', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo')], default='efectivo', max_length=20)),
                ('tipo_envio', models.CharField(choices=[('contraentrega', 'Contraentrega')], default='contraentrega', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad actual disponible para la venta', verbose_name='Stock disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Nivel mínimo antes de mostrar alerta', verbose_name='Stock mínimo')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_producto', to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('producto', 'usuario')},
            },
        ),
    ]
