# Generated by Django 4.2 on 2026-02-23 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('carnes', 'Carnes'), ('bebidas', 'Bebidas'), ('otros', 'Otros'), ('lacteos', 'Lácteos'), ('granos', 'Granos'), ('ornamentales', 'Ornamentales'), ('cereales', 'Cereales'), ('oleaginosas', 'Oleaginosas')], default='otros', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_envio',
            field=models.CharField(choices=[('contraentrega', 'Contraentrega')], default='contraentrega', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('solido', 'Sólido'), ('liquido', 'Líquido')], default='solido', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras'), ('unidad', 'Unidad'), ('litro', 'Litros'), ('mililitro', 'Mililitros')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
    ]
