# Generated by Django 4.2 on 2026-03-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
    ]
