# Generated by Django 4.2 on 2026-02-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_address_postal_code_alter_address_road_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
