# Generated by Django 4.2 on 2026-03-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0006_alter_tienda_options'),
        ('pedidos', '0002_pedidoitem_alter_pedido_options_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda'),
        ),
    ]
