# Generated by Django 4.2 on 2026-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_tienda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedido'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tienda',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('recoger', 'Recoger en tienda')], default='domicilio', max_length=20),
        ),
    ]
