# Generated by Django 4.2 on 2026-03-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0006_alter_tienda_options'),
        ('pedidos', '0005_alter_pedido_options_alter_pedidoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tiendas.tienda'),
        ),
    ]
